import { auth, db } from './firebase.js';
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut, updateProfile, sendPasswordResetEmail } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { ref, onValue, push, set, update, get, query, orderByChild, equalTo } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js';

const $ = (s, r=document) => r.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = v => Number(v || 0).toLocaleString('vi-VN') + ' ₫';
let lang = localStorage.srecLang || 'vi';
let theme = localStorage.srecTheme || 'light';
let currentUser = null;
let hotels = {};
let bookingListener = null;
let chatListener = null;

document.documentElement.dataset.theme = theme;

const text = {
  vi:{home:'Trang chủ',hotels:'Khách sạn',why:'Vì sao chọn SREC',chat:'SREC Chat',login:'Đăng nhập',register:'Đăng ký',logout:'Đăng xuất',account:'Tài khoản',book:'Đặt phòng',search:'Tìm kiếm',destination:'Bạn muốn đi đâu?',checkin:'Nhận phòng',checkout:'Trả phòng',guests:'Số khách',history:'Đặt phòng của tôi',settings:'Cài đặt',support:'Hỗ trợ',admin:'Quản trị',welcome:'Đặt phòng miền Tây theo cách hiện đại',sub:'Khám phá khách sạn đẹp tại Cần Thơ, Bến Tre, An Giang, Kiên Giang và nhiều điểm đến Mekong.',whyTitle:'Một trải nghiệm đặt phòng rõ ràng, nhanh và an tâm.',empty:'Chưa có khách sạn phù hợp.',pending:'Chờ duyệt',approved:'Đã duyệt',checkedIn:'Đã check-in',completed:'Hoàn tất',cancelled:'Đã hủy',rejected:'Từ chối',send:'Gửi',save:'Lưu thay đổi'},
  en:{home:'Home',hotels:'Hotels',why:'Why SREC',chat:'SREC Chat',login:'Login',register:'Register',logout:'Log out',account:'Account',book:'Book now',search:'Search',destination:'Where are you going?',checkin:'Check-in',checkout:'Check-out',guests:'Guests',history:'My bookings',settings:'Settings',support:'Support',admin:'Admin',welcome:'Book your Mekong stay, beautifully',sub:'Discover beautiful hotels across Can Tho, Ben Tre, An Giang, Kien Giang and beyond.',whyTitle:'A clear, fast and confident booking experience.',empty:'No matching hotels.',pending:'Pending',approved:'Approved',checkedIn:'Checked-in',completed:'Completed',cancelled:'Cancelled',rejected:'Rejected',send:'Send',save:'Save changes'}
};
const t = k => text[lang][k] || k;

function transition(fn){
  const cover = document.createElement('div'); cover.className='page-transition'; document.body.appendChild(cover);
  requestAnimationFrame(()=>cover.classList.add('in'));
  setTimeout(()=>{fn(); window.scrollTo({top:0,behavior:'instant'}); cover.classList.remove('in'); setTimeout(()=>cover.remove(),420)},230);
}

function layout(){
  $('#app').innerHTML = `
    <div class="boot" id="boot"><div class="boot-mark">S</div><div><strong>SREC MEKONG</strong><span>HOTEL & TRAVEL</span></div></div>
    <header class="site-header"><a class="brand" href="#home" data-nav><span>SREC</span><b>MEKONG</b></a><nav class="desktop-nav"><a href="#home" data-nav>${t('home')}</a><a href="#hotels" data-nav>${t('hotels')}</a><a href="#why" data-nav>${t('why')}</a><a href="#chat" data-nav>${t('chat')}</a></nav><div class="header-actions"><button class="round" id="langBtn">${lang.toUpperCase()}</button><button class="round" id="themeBtn">${theme==='dark'?'☀':'☾'}</button><span id="accountSlot"></span><button class="mobile-menu" id="mobileMenu">☰</button></div></header>
    <div class="mobile-panel" id="mobilePanel"><a href="#home" data-nav>${t('home')}</a><a href="#hotels" data-nav>${t('hotels')}</a><a href="#why" data-nav>${t('why')}</a><a href="#chat" data-nav>${t('chat')}</a></div>
    <main id="main"></main>
    <footer class="site-footer"><div><div class="brand"><span>SREC</span><b>MEKONG</b></div><p>${t('sub')}</p></div><div><strong>SREC HOTEL</strong><p>Khách sạn • Phòng • Booking • Hỗ trợ realtime</p></div><div><strong>Chính sách</strong><p>Điều khoản sử dụng<br>Chính sách bảo mật<br>Chính sách đặt phòng</p></div><div><strong>Hỗ trợ</strong><p>SREC Chat<br>Email support<br>Booking support</p></div></footer>`;
  $('#langBtn').onclick=()=>{lang=lang==='vi'?'en':'vi';localStorage.srecLang=lang;render()};
  $('#themeBtn').onclick=()=>{theme=theme==='light'?'dark':'light';localStorage.srecTheme=theme;document.documentElement.dataset.theme=theme;};
  $('#mobileMenu').onclick=()=>$('#mobilePanel').classList.toggle('show');
  document.querySelectorAll('[data-nav]').forEach(a=>a.addEventListener('click',()=>$('#mobilePanel')?.classList.remove('show')));
  setTimeout(()=>$('#boot')?.classList.add('hide'),650);
  updateAccount();
}

function updateAccount(){
  const slot=$('#accountSlot'); if(!slot)return;
  if(!currentUser){slot.innerHTML=`<button class="header-login" id="loginBtn">${t('login')}</button><button class="header-register" id="registerBtn">${t('register')}</button>`;$('#loginBtn').onclick=()=>authModal('login');$('#registerBtn').onclick=()=>authModal('register');}
  else slot.innerHTML=`<div class="account-menu"><button class="account-trigger" id="accountTrigger"><span class="avatar">${esc((currentUser.displayName||currentUser.email||'S')[0].toUpperCase())}</span><span class="account-name">${esc(currentUser.displayName||currentUser.email.split('@')[0])}</span>⌄</button><div class="account-pop" id="accountPop"><a href="#profile" data-nav>👤 ${t('account')}</a><a href="#history" data-nav>🧾 ${t('history')}</a><a href="#settings" data-nav>⚙ ${t('settings')}</a>${currentUser.role==='admin'?'<a href="admin.html">🛡 Admin</a>':''}<button id="logoutBtn">↪ ${t('logout')}</button></div></div>`;
  $('#accountTrigger')?.addEventListener('click',e=>{e.stopPropagation();$('#accountPop')?.classList.toggle('show')});
  $('#logoutBtn')?.addEventListener('click',async()=>{await signOut(auth);currentUser=null;location.hash='home';transition(()=>{layout();render()})});
}
window.addEventListener('click',()=>$('#accountPop')?.classList.remove('show'));

function render(){
  updateAccount();
  const p=(location.hash.slice(1)||'home').split('?')[0];
  if(p==='hotels') hotelsPage(); else if(p==='profile') profilePage(); else if(p==='history') historyPage(); else if(p==='settings') settingsPage(); else if(p==='chat') chatPage(); else if(p==='why') homePage(true); else homePage();
}
window.addEventListener('hashchange',()=>transition(render));

function homePage(scrollWhy=false){
  $('#main').innerHTML=`<section class="hero" id="home"><div class="hero-content"><div class="eyebrow"><span></span> SREC HOTEL • MEKONG</div><h1>${t('welcome')}</h1><p>${t('sub')}</p><div class="search-card"><div class="search-field"><small>ĐIỂM ĐẾN</small><input id="heroDest" placeholder="Cần Thơ, Bến Tre, An Giang..."/></div><div class="search-field"><small>${t('checkin')}</small><input id="heroIn" type="date"/></div><div class="search-field"><small>${t('checkout')}</small><input id="heroOut" type="date"/></div><div class="search-field"><small>${t('guests')}</small><select id="heroGuests"><option>1</option><option>2</option><option>3</option><option>4</option><option>5+</option></select></div><button class="search-button" id="heroSearch">⌕ ${t('search')}</button></div><div class="hero-trust"><span>✓ Khách sạn tuyển chọn</span><span>✓ Duyệt booking realtime</span><span>✓ Hỗ trợ SREC Chat</span></div></div><div class="hero-visual"><div class="visual-glow"></div><div class="floating-card fc1"><b>98%</b><span>khách hài lòng</span></div><div class="floating-card fc2"><b>24/7</b><span>hỗ trợ SREC</span></div><div class="visual-center"><span>S</span><strong>MEKONG</strong><small>STAY • DISCOVER • CONNECT</small></div></div></section>
  <section class="section" id="why"><div class="section-heading"><div><div class="eyebrow">SREC STANDARD</div><h2>${t('whyTitle')}</h2></div><a class="text-link" href="#hotels" data-nav>${t('hotels')} →</a></div><div class="feature-grid"><article><i>01</i><h3>Tuyển chọn kỹ</h3><p>Thông tin khách sạn, phòng và tiện ích được trình bày rõ ràng.</p></article><article><i>02</i><h3>Booking minh bạch</h3><p>Mỗi đơn có trạng thái rõ ràng từ chờ duyệt đến hoàn tất.</p></article><article><i>03</i><h3>Realtime</h3><p>Admin duyệt đơn và khách nhận trạng thái gần như ngay lập tức.</p></article><article><i>04</i><h3>Hỗ trợ trực tiếp</h3><p>Trao đổi với SREC qua chat khi cần hỗ trợ đặt phòng.</p></article></div></section>
  <section class="section destinations"><div class="eyebrow">MEKONG JOURNEY</div><h2>Những nơi đáng để bắt đầu</h2><div class="destination-grid"><button onclick="location.hash='hotels'">Cần Thơ <span>Miền sông nước →</span></button><button onclick="location.hash='hotels'">Bến Tre <span>Xứ dừa xanh →</span></button><button onclick="location.hash='hotels'">An Giang <span>Núi & văn hóa →</span></button><button onclick="location.hash='hotels'">Kiên Giang <span>Biển & đảo →</span></button></div></section>
  <section class="section conversation"><div><div class="eyebrow">MEKONG VOICES</div><h2>“Cuối tuần này đi đâu?”</h2><p>“Tìm SREC HOTEL trước, rồi mình chọn nơi để tận hưởng.”</p></div><div class="conversation-card"><div>👩 <span>“Có chỗ nào đẹp mà đặt phòng nhanh không?”</span></div><div class="reply">SREC <span>“Có. Chọn khách sạn, gửi booking — admin duyệt và cập nhật realtime.”</span></div></div></section>`;
  $('#heroSearch').onclick=()=>{localStorage.srecSearch=$('#heroDest').value;location.hash='hotels'};
  if(scrollWhy)setTimeout(()=>$('#why')?.scrollIntoView({behavior:'smooth'}),250);
  loadFeatured();
}

function loadFeatured(){onValue(ref(db,'hotels'),s=>{hotels=s.val()||{}; const sec=$('#featuredHotels'); if(sec)sec.innerHTML=Object.entries(hotels).slice(0,6).map(([id,h])=>hotelCard(id,h)).join('')||''})}
function roomPrice(room){const n=String(room?.name||'').toLowerCase(); if(n.includes('đôi')||n.includes('double')||n.includes('twin')) return 300000; return 200000;}
function normalizedRooms(h){const src=h.rooms&&Object.keys(h.rooms).length?h.rooms:{single:{name:'Phòng đơn',price:200000},double:{name:'Phòng đôi',price:300000}}; return Object.entries(src).map(([id,r])=>[id,{...r,price:roomPrice(r)}]);}
function hotelCard(id,h){const img=Object.values(h.images||{})[0]||h.cover||'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=85';return `<article class="hotel-card" data-id="${id}"><div class="hotel-img"><img src="${img}" loading="lazy"><span class="rating-pill">★ ${Number(h.rating||0).toFixed(1)}</span></div><div class="hotel-info"><div class="hotel-location">📍 ${esc(h.address||'Mekong')}</div><h3>${esc(h.name||'SREC HOTEL')}</h3><div class="amenity-line">${(h.amenities||['Wi-Fi','Điều hòa','Bữa sáng']).slice(0,3).map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="hotel-bottom"><b>${money(Math.min(...normalizedRooms(h).map(([,r])=>r.price)))} <small>/ đêm</small></b><button class="small-primary">${t('book')} →</button></div></div></article>`}

document.addEventListener('click',e=>{const c=e.target.closest('.hotel-card');if(c){e.preventDefault();location.hash='hotel-'+c.dataset.id}});

function hotelsPage(){
  $('#main').innerHTML=`<section class="section top-space"><div class="section-heading"><div><div class="eyebrow">SREC HOTEL</div><h1>${t('hotels')}</h1><p>Chọn điểm đến, xem phòng và gửi yêu cầu đặt phòng.</p></div></div><div class="filter-card"><input id="hotelQuery" placeholder="⌕ ${t('destination')}" value="${esc(localStorage.srecSearch||'')}"><select id="hotelSort"><option value="rating">Đánh giá cao nhất</option><option value="price">Giá thấp nhất</option><option value="name">Tên A-Z</option></select></div><div id="hotelGrid" class="hotel-grid"></div></section>`;
  onValue(ref(db,'hotels'),s=>{hotels=s.val()||{};applyHotelFilter()});
  $('#hotelQuery').oninput=applyHotelFilter;$('#hotelSort').onchange=applyHotelFilter;
  function applyHotelFilter(){let q=($('#hotelQuery')?.value||'').toLowerCase().trim();let arr=Object.entries(hotels).filter(([_,h])=>(`${h.name||''} ${h.address||''} ${(h.amenities||[]).join(' ')}`).toLowerCase().includes(q));const sort=$('#hotelSort')?.value;if(sort==='price')arr.sort((a,b)=>(a[1].price||0)-(b[1].price||0));else if(sort==='name')arr.sort((a,b)=>(a[1].name||'').localeCompare(b[1].name||''));else arr.sort((a,b)=>(b[1].rating||0)-(a[1].rating||0));$('#hotelGrid').innerHTML=arr.map(([id,h])=>hotelCard(id,h)).join('')||`<div class="empty-state">${t('empty')}</div>`}
}

function hotelDetail(id){const h=hotels[id];if(!h){location.hash='hotels';return}const imgs=Object.values(h.images||{}).slice(0,15);$('#main').innerHTML=`<section class="section top-space"><button class="back-btn" onclick="location.hash='hotels'">← ${t('hotels')}</button><div class="detail-top"><div><div class="eyebrow">SREC HOTEL</div><h1>${esc(h.name)}</h1><p>📍 ${esc(h.address||'Mekong')}</p><div class="detail-rating">★ ${Number(h.rating||0).toFixed(1)} <span>Được đánh giá bởi khách SREC</span></div></div><button class="primary-btn" id="bookHotel">${t('book')} →</button></div><div class="gallery">${(imgs.length?imgs:['https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=85']).map((x,i)=>`<img class="g${i}" src="${x}" loading="lazy">`).join('')}</div><div class="detail-grid"><article class="glass-panel"><h2>Tiện ích</h2><div class="tag-list">${(h.amenities||['Wi-Fi','Điều hòa','Bãi đỗ xe','Bữa sáng']).map(x=>`<span>✓ ${esc(x)}</span>`).join('')}</div><h2>Mô tả</h2><p>${esc(h.description||'Không gian lưu trú được SREC giới thiệu cho hành trình Mekong.')}</p></article><article class="glass-panel"><h2>Phòng</h2>${normalizedRooms(h).map(([rid,r])=>`<div class="room-card"><div><b>${esc(r.name||rid)}</b><small>Phòng tiêu chuẩn SREC</small></div><strong>${money(roomPrice(r))}<small>/ đêm</small></strong></div>`).join('')}</article></div></section>`;$('#bookHotel').onclick=()=>bookingForm(id)}

function bookingForm(hotelId){if(!currentUser){authModal('login','Đăng nhập để tiếp tục đặt phòng');return}const h=hotels[hotelId], rooms=normalizedRooms(h);$('#main').innerHTML=`<section class="section top-space narrow"><button class="back-btn" onclick="location.hash='hotel-${hotelId}'">← ${esc(h.name)}</button><div class="section-heading"><div><div class="eyebrow">SECURE BOOKING</div><h1>${t('book')}</h1><p>${esc(h.name)} • ${esc(h.address||'Mekong')}</p></div></div><form class="booking-form glass-panel" id="bookingForm"><div class="form-grid"><label>Họ tên<input id="bName" required value="${esc(currentUser.displayName||'')}"></label><label>Email<input value="${esc(currentUser.email||'')}" disabled></label><label>Số điện thoại<input id="bPhone" required value="${esc(currentUser.phone||'')}"></label><label>Phòng<select id="bRoom">${rooms.map(([id,r])=>`<option value="${id}" data-price="${roomPrice(r)}">${esc(r.name||id)} — ${money(roomPrice(r))}/đêm</option>`).join('')}</select></label><label>${t('checkin')}<input id="bIn" type="date" required></label><label>${t('checkout')}<input id="bOut" type="date" required></label><label>${t('guests')}<select id="bGuests"><option>1</option><option>2</option><option>3</option><option>4</option><option>5+</option></select></label></div><div class="booking-summary"><div><span>Trạng thái</span><b>Chờ admin duyệt</b></div><div><span>Giá dự kiến</span><b id="bookingTotal">—</b></div></div><button class="primary-btn wide-btn">Gửi yêu cầu đặt phòng</button><p class="form-note">Sau khi gửi, đơn sẽ ở trạng thái chờ duyệt. Bạn có thể theo dõi realtime trong “Đặt phòng của tôi”.</p></form></section>`;
  const calc=()=>{const a=new Date($('#bIn').value),b=new Date($('#bOut').value),n=Math.max(0,Math.round((b-a)/86400000));const price=Number($('#bRoom').selectedOptions[0]?.dataset.price||0);$('#bookingTotal').textContent=n?money(n*price):'—'};$('#bIn').onchange=calc;$('#bOut').onchange=calc;$('#bRoom').onchange=calc;
  $('#bookingForm').onsubmit=async e=>{e.preventDefault();const a=new Date($('#bIn').value),b=new Date($('#bOut').value),n=Math.round((b-a)/86400000);if(!n||n<1)return toast('Ngày trả phòng phải sau ngày nhận phòng.');const room=$('#bRoom').selectedOptions[0];const id=push(ref(db,'bookings')).key;const data={userId:currentUser.uid,hotelId,hotelName:h.name,roomName:room.textContent.split('—')[0].trim(),roomId:$('#bRoom').value,guestName:$('#bName').value.trim(),email:currentUser.email,phone:$('#bPhone').value.trim(),checkIn:$('#bIn').value,checkOut:$('#bOut').value,guests:$('#bGuests').value,nights:n,total:n*Number(room.dataset.price||0),status:'pending',createdAt:Date.now(),updatedAt:Date.now()};await set(ref(db,'bookings/'+id),data);await update(ref(db,'users/'+currentUser.uid),{name:data.guestName,phone:data.phone,email:currentUser.email});await set(ref(db,`notifications/${currentUser.uid}/${push(ref(db,`notifications/${currentUser.uid}`)).key}`),{title:'Đã gửi booking',message:`${h.name} đang chờ admin duyệt.`,createdAt:Date.now(),read:false});toast('Đã gửi yêu cầu đặt phòng ✓');location.hash='history'};
}

function historyPage(){if(!currentUser){authModal('login');return}$('#main').innerHTML=`<section class="section top-space"><div class="eyebrow">MY SREC</div><h1>${t('history')}</h1><div id="bookingList" class="booking-list"></div></section>`;bookingListener?.();bookingListener=onValue(query(ref(db,'bookings'),orderByChild('userId'),equalTo(currentUser.uid)),s=>{const arr=Object.entries(s.val()||{}).sort((a,b)=>b[1].createdAt-a[1].createdAt);$('#bookingList').innerHTML=arr.map(([id,b])=>`<article class="booking-item"><div><span class="status-pill ${b.status}">${t(b.status)}</span><h3>${esc(b.hotelName)}</h3><p>${esc(b.roomName||'Phòng')} • ${b.checkIn} → ${b.checkOut} • ${b.guests} khách</p><small>${new Date(b.createdAt).toLocaleString('vi-VN')}</small></div><strong>${money(b.total)}</strong></article>`).join('')||`<div class="empty-state">Bạn chưa có booking nào.</div>`})}

function profilePage(){if(!currentUser){authModal('login');return}$('#main').innerHTML=`<section class="section top-space narrow"><div class="eyebrow">MY PROFILE</div><h1>${t('account')}</h1><div class="profile-card glass-panel"><div class="big-avatar">${esc((currentUser.displayName||currentUser.email||'S')[0].toUpperCase())}</div><h2>${esc(currentUser.displayName||'SREC Guest')}</h2><p>${esc(currentUser.email)}</p><div class="profile-meta"><span>📱 ${esc(currentUser.phone||'Chưa cập nhật SĐT')}</span><span>✓ Tài khoản xác thực</span></div><div class="profile-actions"><a class="primary-btn" href="#settings">${t('settings')}</a><a class="secondary-btn" href="#history">${t('history')}</a></div></div></section>`}

function settingsPage(){if(!currentUser){authModal('login');return}$('#main').innerHTML=`<section class="section top-space narrow"><div class="eyebrow">ACCOUNT SETTINGS</div><h1>${t('settings')}</h1><form class="glass-panel settings-form" id="settingsForm"><label>Họ tên<input id="sName" value="${esc(currentUser.displayName||'')}"></label><label>Số điện thoại<input id="sPhone" value="${esc(currentUser.phone||'')}"></label><label>Email<input value="${esc(currentUser.email||'')}" disabled></label><button class="primary-btn">${t('save')}</button></form><div class="glass-panel danger-panel"><h3>Bảo mật</h3><p>Gửi email đặt lại mật khẩu nếu bạn muốn đổi mật khẩu.</p><button class="secondary-btn" id="resetPassword">Đặt lại mật khẩu</button></div><div class="glass-panel"><h3>Đăng xuất</h3><p>Khi đăng xuất, SREC sẽ đưa bạn trở lại trang đầu.</p><button class="danger-btn" id="settingsLogout">${t('logout')}</button></div></section>`;$('#settingsForm').onsubmit=async e=>{e.preventDefault();await updateProfile(currentUser,{displayName:$('#sName').value.trim()});await update(ref(db,'users/'+currentUser.uid),{name:$('#sName').value.trim(),phone:$('#sPhone').value.trim(),email:currentUser.email});toast('Đã lưu thay đổi ✓');profilePage()};$('#resetPassword').onclick=async()=>{await sendPasswordResetEmail(auth,currentUser.email);toast('Đã gửi email đặt lại mật khẩu.')};$('#settingsLogout').onclick=async()=>{await signOut(auth);currentUser=null;location.hash='home';layout();render()}}

function chatPage(){if(!currentUser){authModal('login');return}$('#main').innerHTML=`<section class="section top-space narrow"><div class="eyebrow">SREC SUPPORT</div><h1>${t('chat')}</h1><div class="chat-box glass-panel"><div id="messages" class="messages"></div><form id="chatForm"><input id="chatInput" placeholder="Nhập tin nhắn cho SREC..."><button class="primary-btn">${t('send')}</button></form></div></section>`;chatListener?.();chatListener=onValue(ref(db,`chats/${currentUser.uid}/messages`),s=>{const arr=Object.values(s.val()||{}).sort((a,b)=>a.createdAt-b.createdAt);$('#messages').innerHTML=arr.map(m=>`<div class="chat-msg ${m.senderId===currentUser.uid?'me':''}"><b>${m.senderRole==='admin'?'SREC':'Bạn'}</b><span>${esc(m.text)}</span></div>`).join('')||'<div class="chat-empty">Xin chào! SREC sẵn sàng hỗ trợ bạn.</div>';$('#messages').scrollTop=$('#messages').scrollHeight});$('#chatForm').onsubmit=async e=>{e.preventDefault();const val=$('#chatInput').value.trim();if(!val)return;const id=push(ref(db,`chats/${currentUser.uid}/messages`)).key;await set(ref(db,`chats/${currentUser.uid}/messages/${id}`),{senderId:currentUser.uid,senderRole:'user',text:val,createdAt:Date.now()});await update(ref(db,`chats/${currentUser.uid}`),{userId:currentUser.uid,updatedAt:Date.now(),lastMessage:val});$('#chatInput').value=''}}

function authModal(mode='login',note=''){const m=document.createElement('div');m.className='modal-wrap';m.innerHTML=`<div class="auth-modal"><button class="modal-close">×</button><div class="auth-brand"><span>S</span><div><b>SREC MEKONG</b><small>HOTEL & TRAVEL</small></div></div><div class="auth-tabs"><button class="${mode==='login'?'active':''}" data-mode="login">${t('login')}</button><button class="${mode==='register'?'active':''}" data-mode="register">${t('register')}</button></div><p class="auth-note">${esc(note)}</p><div id="authBody"></div></div>`;document.body.appendChild(m);m.querySelector('.modal-close').onclick=()=>m.remove();m.addEventListener('click',e=>{if(e.target===m)m.remove()});m.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{m.remove();authModal(b.dataset.mode)});renderAuthBody(m,mode)}
function renderAuthBody(m,mode){$('#authBody',m).innerHTML=mode==='login'?`<form id="authForm" class="auth-form"><label>Email<input id="aEmail" type="email" required autocomplete="email"></label><label>Mật khẩu<input id="aPass" type="password" required autocomplete="current-password"></label><button class="primary-btn wide-btn">${t('login')}</button><button type="button" class="text-btn" id="forgot">Quên mật khẩu?</button></form>`:`<form id="authForm" class="auth-form"><label>Họ tên<input id="aName" required></label><label>Số điện thoại<input id="aPhone" required></label><label>Email<input id="aEmail" type="email" required autocomplete="email"></label><label>Mật khẩu<input id="aPass" type="password" minlength="7" required autocomplete="new-password"></label><small>Mật khẩu tối thiểu 7 ký tự.</small><button class="primary-btn wide-btn">${t('register')}</button></form>`;$('#authForm',m).onsubmit=async e=>{e.preventDefault();try{if(mode==='login'){await signInWithEmailAndPassword(auth,$('#aEmail',m).value.trim(),$('#aPass',m).value)}else{const cred=await createUserWithEmailAndPassword(auth,$('#aEmail',m).value.trim(),$('#aPass',m).value);await updateProfile(cred.user,{displayName:$('#aName',m).value.trim()});await set(ref(db,'users/'+cred.user.uid),{name:$('#aName',m).value.trim(),phone:$('#aPhone',m).value.trim(),email:cred.user.email,role:'user',createdAt:Date.now()})}m.remove();toast(mode==='login'?'Đăng nhập thành công ✓':'Tạo tài khoản thành công ✓')}catch(err){toast(authError(err))}};$('#forgot',m)?.addEventListener('click',async()=>{const email=$('#aEmail',m).value.trim();if(!email)return toast('Nhập email trước.');try{await sendPasswordResetEmail(auth,email);toast('Đã gửi email đặt lại mật khẩu.')}catch(err){toast(authError(err))}})}
function authError(e){const c=e?.code||'';if(c.includes('invalid-credential'))return 'Email hoặc mật khẩu không đúng.';if(c.includes('email-already-in-use'))return 'Email này đã được đăng ký.';if(c.includes('weak-password'))return 'Mật khẩu quá yếu.';if(c.includes('invalid-email'))return 'Email không hợp lệ.';return 'Không thể thực hiện. Kiểm tra Firebase Authentication.'}
function toast(msg){let x=document.createElement('div');x.className='toast';x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.classList.add('hide'),2400);setTimeout(()=>x.remove(),2800)}

onAuthStateChanged(auth, async u=>{currentUser=u; if(u){try{const s=await get(ref(db,'users/'+u.uid));currentUser.role=(s.val()==='admin'||s.val()?.role==='admin')?'admin':(s.val()?.role||'user');currentUser.phone=s.val()?.phone||''}catch{} } layout(); render(); if(location.hash.startsWith('#hotel-'))hotelDetail(location.hash.slice(7));});
window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#hotel-')){const id=location.hash.slice(7);transition(()=>hotelDetail(id))}});
